### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by staceysych23** [linxianxi/react-selectable-box#29]
### 🐛 bug 描述

Hey, I discovered a bug in versions after v.1.6.0

Context: When I first make a selection (img below)
![image](https://github.com/linxianxi/react-selectable-box/assets/117638958/e8518fa7-56ba-46da-a07d-846c556f81ad)

and then I select another row. (img below)
![image](https://github.com/linxianxi/react-selectable-box/assets/117638958/bf1e34b6-4e5b-4c0b-99a8-c0131a049b87)

For a second `isSelecting` prop for previously selected values will be `true`. (img below)
![image](https://github.com/linxianxi/react-selectable-box/assets/117638958/51bdcb5f-abd0-481a-b22f-b2d2358acefa)

```typescript
const { setNodeRef, isSelected, isSelecting } =
    useSelectable({
      value,
    });

console.log(value, console.log(value, isSelected, isSelecting););

``` 

Could you please take a look as it's casing an issue in my project?
Many thanks

**Comment by linxianxi** [comment]
It's not a bug, it's expected, you want isAdding?

**Comment by staceysych23** [comment]
I can't understand why isSelecting is true for previously selected values? I'm not selecting them atm. It started happening in version 1.6.0
https://github.com/linxianxi/react-selectable-box/assets/117638958/492b4c7c-3915-4420-871f-ed48db56084f

**Comment by linxianxi** [comment]
![image](https://github.com/linxianxi/react-selectable-box/assets/47104575/a48d7eae-cd99-4b39-91b8-8ba57086bf2b)
In your video, your console.log is isSelected && isSelecting. I tested isSelecting in the latest version and it is false.

**Comment by staceysych23** [comment]
That's what I did. I opened a codesandbox and forked it.

See another video


https://github.com/linxianxi/react-selectable-box/assets/117638958/0b1df42e-a438-4746-b2ea-f7d3d5cd70ba

**Comment by staceysych23** [comment]
https://codesandbox.io/p/sandbox/sad-sky-lcg3qc?file=%2FApp.tsx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsygp6r100063b6jpjnltvgi%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsygp6r100023b6jqmc6y0lz%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsygp6r100033b6jphm8qf1s%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsygp6r100053b6joz3d9v6f%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsygp6r100023b6jqmc6y0lz%2522%253A%257B%2522id%2522%253A%2522clsygp6r100023b6jqmc6y0lz%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsyli0za00023b6jieojkq26%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsyli0za00023b6jieojkq26%2522%257D%252C%2522clsygp6r100053b6joz3d9v6f%2522%253A%257B%2522id%2522%253A%2522clsygp6r100053b6joz3d9v6f%2522%252C%2522activeTabId%2522%253A%2522clsyuf61z00ia3b6jd7lxs2ky%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clsyuf61z00ia3b6jd7lxs2ky%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clsygp6r100033b6jphm8qf1s%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsygp6r100033b6jphm8qf1s%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by staceysych23** [comment]
In the docs it says: `
isSelecting | Whether it is currently being selected | boolean
`

But elements 0,1,2 from the video are not being selected when I select elements 10,11,12. Then why `isSelected` is still true for them?

**Comment by staceysych23** [comment]
The issue disappears if I downgrade the version to 1.5.0. Please, see the video

https://github.com/linxianxi/react-selectable-box/assets/117638958/13c93695-48c1-458a-8d6c-151e61678b17

**Comment by staceysych23** [comment]
Thanks, it's been solved for me :)
