### ISSUE TITLE
🐛[BUG] Virtualized List, Some items not selected

### ISSUE THREAD

**Issue by aarongjy97** [linxianxi/react-selectable-box#41]
### 🐛 Description
When selecting in a virtualized list, selecting items (not all) can cause some elements to be not selected

### 💻 Reproduction link
https://linxianxi.github.io/react-selectable-box/guides/virtual-list

### 📷 Steps to reproduce
1. Select up to 1000 elements
2. Scroll all the way up, notice first 2 rows are unselected

### 🏞 What is expected?
All 1000 elements to be selected

### What is actually happening?
First 2 rows are unselected

### © Version information
- browser - Chrome 128.0.6613.138
- system - MacOS Sequoia 15.0

**Comment by linxianxi** [comment]
Can you record a video?

**Comment by aarongjy97** [comment]
@linxianxi here you go~! 
https://github.com/user-attachments/assets/8f4bee28-510e-41c6-a7ff-28feb8021b4c

**Comment by linxianxi** [comment]
The virtual scrolling is too fast, causing no mount to be skipped for rendering, and it is impossible to determine the specific location. Currently, only elements that have been mounted will be selected.

**Comment by aarongjy97** [comment]
> The virtual scrolling is too fast, causing no mount to be skipped for rendering, and it is impossible to determine the specific location. Currently, only elements that have been mounted will be selected.

@linxianxi is this expected? scrolling at this speed to the bottom also causes only the top few rows to be not selected 😢

**Comment by linxianxi** [comment]
It seems to be a bug, because I usually use a trackpad and do not encounter this problem, I will check this bug

**Comment by aarongjy97** [comment]
> It seems to be a bug, because I usually use a trackpad and do not encounter this problem, I will check this bug

@linxianxi interesting bug 🤔 i tried trackpad and it is fine too 
i'm using a Logitech Master MX3 mouse, not sure if it helps~

**Comment by linxianxi** [comment]
Fixed in 1.9.5, you can try again
