### ISSUE TITLE
🐛[BUG]  在id="drag-container"元素下的子元素中，移动端touch事件等不能正常触发click

### ISSUE THREAD

**Issue by jikoczl** [linxianxi/react-selectable-box#44]
### 🐛 Description

```
<div id="drag-container">
<Button onCLick=(()=>console.info(1))>按钮</Button>
</div>
```

如果是电脑端，点击事件可以正常触发，但是移动端貌似不行

**Comment by linxianxi** [comment]
虽然有支持移动端，但是真的在移动端用框选不会不好操作吗😂

**Comment by Sir3eBpA** [comment]
This causes a:
```
Uncaught ReferenceError: TouchEvent is not defined
    onMouseMove2 Selectable.js:187
    onMouseDown2 Selectable.js:285
    Selectable Selectable.js:294
```
exception so I'm not sure if this fix is good enough

**Comment by linxianxi** [comment]
> This causes a: 这会导致：
> 
> ```
> Uncaught ReferenceError: TouchEvent is not defined
>     onMouseMove2 Selectable.js:187
>     onMouseDown2 Selectable.js:285
>     Selectable Selectable.js:294
> ```
> 
> exception so I'm not sure if this fix is good enoughexception 的 intent 的 intent so 我不确定这个修复程序是否足够好

Can you tell me your environment? Firefox?

**Comment by Sir3eBpA** [comment]
Yup firefox 131.0.3

**Comment by linxianxi** [comment]
@Sir3eBpA Fixed, try 1.9.8
