### ISSUE TITLE
🐛[BUG] The horizontal scrolling functionality is not working

### ISSUE THREAD

**Issue by KevinAnass** [linxianxi/react-selectable-box#48]
I'll help you create a bug report template for the horizontal scrolling issue:

🐛 Description
The horizontal scrolling functionality is not working for a flex container that displays items in a single row. Despite setting overflowX: "auto", the container does not allow horizontal scrolling when items overflow.

📷 Steps to reproduce
Create a flex container with multiple items: 
```
<div
id="drag-container"
className="flex flex-row flex-nowrap"
style={{
  gap: 20,
  padding: 20,
  border: "1px solid #ccc",
  overflowX: "auto"
}}
>
{list.map((i) => (
  <Item key={i} value={i} rule={rule} />
))}
</div>
```
Add enough items to overflow the container width
Try to scroll horizontally to view overflow items

🏞 What is expected?

User should be able to scroll horizontally to select all items 

What is actually happening? 
Unable to scroll horizontally to view overflow items 

![image](https://github.com/user-attachments/assets/3a135b32-21e0-4eb6-b5d7-4893451e4419)

**Comment by linxianxi** [comment]
You should set `scrollContainer`.
