### ISSUE TITLE
🐛[BUG] click to select demo 点击过快，可能会选不中

### ISSUE THREAD

**Issue by linxianxi** [linxianxi/react-selectable-box#5]
### 🐛 bug 描述

click to select demo 点击过快，可能会选不中

### © 版本信息

- react-selectable-fast 版本: [e.g. 1.0.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lovetingyuan** [comment]
这个距离最好提供一个选项，1px太小了

**Comment by lovetingyuan** [comment]
就是快速点击 就会触发onStart
